# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eingabewindow.ui'
#
# Created: Mon Aug 28 21:16:43 2017
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_EingabeWindow(object):
    def setupUi(self, EingabeWindow):
        EingabeWindow.setObjectName(_fromUtf8("EingabeWindow"))
        EingabeWindow.resize(474, 530)
        self.resetButton = QtGui.QPushButton(EingabeWindow)
        self.resetButton.setGeometry(QtCore.QRect(180, 470, 131, 41))
        self.resetButton.setObjectName(_fromUtf8("resetButton"))
        self.groupBox_Eingabe = QtGui.QGroupBox(EingabeWindow)
        self.groupBox_Eingabe.setGeometry(QtCore.QRect(30, 10, 401, 451))
        self.groupBox_Eingabe.setStyleSheet(_fromUtf8("QPushButton{ color: black}\n"
"QPushButton{background: grey; border: 1px solid}\n"
"\n"
"QPushButton:checked{\n"
"    background: orange;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1px solid orange;\n"
"}"))
        self.groupBox_Eingabe.setObjectName(_fromUtf8("groupBox_Eingabe"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.groupBox_Eingabe)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 30, 320, 401))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.button00 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button00.sizePolicy().hasHeightForWidth())
        self.button00.setSizePolicy(sizePolicy)
        self.button00.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button00.setAcceptDrops(False)
        self.button00.setText(_fromUtf8(""))
        self.button00.setCheckable(True)
        self.button00.setFlat(True)
        self.button00.setObjectName(_fromUtf8("button00"))
        self.gridLayout.addWidget(self.button00, 0, 0, 1, 1)
        self.button01 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button01.sizePolicy().hasHeightForWidth())
        self.button01.setSizePolicy(sizePolicy)
        self.button01.setText(_fromUtf8(""))
        self.button01.setCheckable(True)
        self.button01.setFlat(True)
        self.button01.setObjectName(_fromUtf8("button01"))
        self.gridLayout.addWidget(self.button01, 0, 1, 1, 1)
        self.button02 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button02.sizePolicy().hasHeightForWidth())
        self.button02.setSizePolicy(sizePolicy)
        self.button02.setText(_fromUtf8(""))
        self.button02.setCheckable(True)
        self.button02.setFlat(True)
        self.button02.setObjectName(_fromUtf8("button02"))
        self.gridLayout.addWidget(self.button02, 0, 2, 1, 1)
        self.button03 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button03.sizePolicy().hasHeightForWidth())
        self.button03.setSizePolicy(sizePolicy)
        self.button03.setText(_fromUtf8(""))
        self.button03.setCheckable(True)
        self.button03.setFlat(True)
        self.button03.setObjectName(_fromUtf8("button03"))
        self.gridLayout.addWidget(self.button03, 0, 3, 1, 1)
        self.button04 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button04.sizePolicy().hasHeightForWidth())
        self.button04.setSizePolicy(sizePolicy)
        self.button04.setText(_fromUtf8(""))
        self.button04.setCheckable(True)
        self.button04.setFlat(True)
        self.button04.setObjectName(_fromUtf8("button04"))
        self.gridLayout.addWidget(self.button04, 1, 0, 1, 1)
        self.button05 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button05.sizePolicy().hasHeightForWidth())
        self.button05.setSizePolicy(sizePolicy)
        self.button05.setText(_fromUtf8(""))
        self.button05.setCheckable(True)
        self.button05.setFlat(True)
        self.button05.setObjectName(_fromUtf8("button05"))
        self.gridLayout.addWidget(self.button05, 1, 1, 1, 1)
        self.button06 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button06.sizePolicy().hasHeightForWidth())
        self.button06.setSizePolicy(sizePolicy)
        self.button06.setText(_fromUtf8(""))
        self.button06.setCheckable(True)
        self.button06.setFlat(True)
        self.button06.setObjectName(_fromUtf8("button06"))
        self.gridLayout.addWidget(self.button06, 1, 2, 1, 1)
        self.button07 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button07.sizePolicy().hasHeightForWidth())
        self.button07.setSizePolicy(sizePolicy)
        self.button07.setText(_fromUtf8(""))
        self.button07.setCheckable(True)
        self.button07.setFlat(True)
        self.button07.setObjectName(_fromUtf8("button07"))
        self.gridLayout.addWidget(self.button07, 1, 3, 1, 1)
        self.button08 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button08.sizePolicy().hasHeightForWidth())
        self.button08.setSizePolicy(sizePolicy)
        self.button08.setText(_fromUtf8(""))
        self.button08.setCheckable(True)
        self.button08.setFlat(True)
        self.button08.setObjectName(_fromUtf8("button08"))
        self.gridLayout.addWidget(self.button08, 2, 0, 1, 1)
        self.button09 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button09.sizePolicy().hasHeightForWidth())
        self.button09.setSizePolicy(sizePolicy)
        self.button09.setText(_fromUtf8(""))
        self.button09.setCheckable(True)
        self.button09.setFlat(True)
        self.button09.setObjectName(_fromUtf8("button09"))
        self.gridLayout.addWidget(self.button09, 2, 1, 1, 1)
        self.button10 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button10.sizePolicy().hasHeightForWidth())
        self.button10.setSizePolicy(sizePolicy)
        self.button10.setText(_fromUtf8(""))
        self.button10.setCheckable(True)
        self.button10.setFlat(True)
        self.button10.setObjectName(_fromUtf8("button10"))
        self.gridLayout.addWidget(self.button10, 2, 2, 1, 1)
        self.button11 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button11.sizePolicy().hasHeightForWidth())
        self.button11.setSizePolicy(sizePolicy)
        self.button11.setText(_fromUtf8(""))
        self.button11.setCheckable(True)
        self.button11.setFlat(True)
        self.button11.setObjectName(_fromUtf8("button11"))
        self.gridLayout.addWidget(self.button11, 2, 3, 1, 1)
        self.button12 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button12.sizePolicy().hasHeightForWidth())
        self.button12.setSizePolicy(sizePolicy)
        self.button12.setText(_fromUtf8(""))
        self.button12.setCheckable(True)
        self.button12.setFlat(True)
        self.button12.setObjectName(_fromUtf8("button12"))
        self.gridLayout.addWidget(self.button12, 4, 0, 1, 1)
        self.button13 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button13.sizePolicy().hasHeightForWidth())
        self.button13.setSizePolicy(sizePolicy)
        self.button13.setText(_fromUtf8(""))
        self.button13.setCheckable(True)
        self.button13.setFlat(True)
        self.button13.setObjectName(_fromUtf8("button13"))
        self.gridLayout.addWidget(self.button13, 4, 1, 1, 1)
        self.button14 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button14.sizePolicy().hasHeightForWidth())
        self.button14.setSizePolicy(sizePolicy)
        self.button14.setText(_fromUtf8(""))
        self.button14.setCheckable(True)
        self.button14.setFlat(True)
        self.button14.setObjectName(_fromUtf8("button14"))
        self.gridLayout.addWidget(self.button14, 4, 2, 1, 1)
        self.button15 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button15.sizePolicy().hasHeightForWidth())
        self.button15.setSizePolicy(sizePolicy)
        self.button15.setText(_fromUtf8(""))
        self.button15.setCheckable(True)
        self.button15.setFlat(True)
        self.button15.setObjectName(_fromUtf8("button15"))
        self.gridLayout.addWidget(self.button15, 4, 3, 1, 1)
        self.button16 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button16.sizePolicy().hasHeightForWidth())
        self.button16.setSizePolicy(sizePolicy)
        self.button16.setText(_fromUtf8(""))
        self.button16.setCheckable(True)
        self.button16.setFlat(True)
        self.button16.setObjectName(_fromUtf8("button16"))
        self.gridLayout.addWidget(self.button16, 6, 0, 1, 1)
        self.button17 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button17.sizePolicy().hasHeightForWidth())
        self.button17.setSizePolicy(sizePolicy)
        self.button17.setText(_fromUtf8(""))
        self.button17.setCheckable(True)
        self.button17.setFlat(True)
        self.button17.setObjectName(_fromUtf8("button17"))
        self.gridLayout.addWidget(self.button17, 6, 1, 1, 1)
        self.button18 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button18.sizePolicy().hasHeightForWidth())
        self.button18.setSizePolicy(sizePolicy)
        self.button18.setText(_fromUtf8(""))
        self.button18.setCheckable(True)
        self.button18.setFlat(True)
        self.button18.setObjectName(_fromUtf8("button18"))
        self.gridLayout.addWidget(self.button18, 6, 2, 1, 1)
        self.button19 = QtGui.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button19.sizePolicy().hasHeightForWidth())
        self.button19.setSizePolicy(sizePolicy)
        self.button19.setText(_fromUtf8(""))
        self.button19.setCheckable(True)
        self.button19.setFlat(True)
        self.button19.setObjectName(_fromUtf8("button19"))
        self.gridLayout.addWidget(self.button19, 6, 3, 1, 1)

        self.retranslateUi(EingabeWindow)
        QtCore.QMetaObject.connectSlotsByName(EingabeWindow)

    def retranslateUi(self, EingabeWindow):
        EingabeWindow.setWindowTitle(_translate("EingabeWindow", "Form", None))
        self.resetButton.setText(_translate("EingabeWindow", "zurücksetzen", None))
        self.groupBox_Eingabe.setTitle(_translate("EingabeWindow", "Eingabe", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EingabeWindow = QtGui.QWidget()
    ui = Ui_EingabeWindow()
    ui.setupUi(EingabeWindow)
    EingabeWindow.show()
    sys.exit(app.exec_())

